[tool.black]
line-length = 88
target-version = ["py312"]
exclude = '''
/(
    migrations
  | venv
  | env
  | static
  | media
)/
'''

[tool.isort]
profile = "black"
line_length = 88
skip = ["migrations", "venv", "env"]

[tool.ruff]
line-length = 88
exclude = ["migrations", "venv", "env"]
select = [
  "E", "F",   # pyflakes + pycodestyle errors
  "I",        # import sorting
  "DJ",       # Django-specific rules
]
ignore = [
  "E501",     # line length (Black handles it)
]

[tool.djlint]
profile="django"
indent=4
ignore="H031,H006"  # example: ignore rules you donâ€™t care about
